name = "rr7-cf-template"
compatibility_date = "2024-10-02"
workers_dev = true

main = "build/server/index.js"
assets = { directory = "build/client" }

build = { command = "pnpm build" }

[observability]
enabled = true

[env.development]

[env.development.vars]
SESSION_SECRET = "super-secret"
